# 모범 답안 참고 
# 서브 쿼리 아이디어까지는 생각햇으나 IN 연산자 도입 생각 하지 못함 
SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE,FAVORITES) IN (SELECT FOOD_TYPE,MAX(FAVORITES)FROM REST_INFO GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC; 