SELECT P.PRODUCT_ID,P.PRODUCT_NAME,SUM(P.PRICE*O.AMOUNT) AS 'TOTAL_SALES'
FROM (SELECT *
FROM FOOD_ORDER
WHERE YEAR(PRODUCE_DATE)=2022 AND MONTH(PRODUCE_DATE)=5) O INNER JOIN 
FOOD_PRODUCT P USING (PRODUCT_ID)
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;