SELECT FLAVOR
FROM (SELECT *,(H.TOTAL_ORDER + J.ORDER) AS 'TOTAL'
FROM FIRST_HALF H JOIN (SELECT FLAVOR,SUM(TOTAL_ORDER) AS 'ORDER' FROM JULY GROUP BY FLAVOR) J USING (FLAVOR)
ORDER BY TOTAL DESC) T
LIMIT 3;